# Generated by Django 5.0.9 on 2026-08-18 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(default='fa-solid fa-toolbox', help_text='Font Awesome class, e.g. "fa-solid fa-bolt"', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='navy', help_text='Brand accent key: navy, green, orange, blue, gold', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Tell customers about your experience and specialties.', max_length=1000)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('location', models.CharField(help_text='Area / locality, e.g. "MG Road"', max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Optional: pin your exact location so nearby customers find you.', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
                ('is_available', models.BooleanField(default=True, help_text='Currently accepting new bookings')),
                ('availability_days', models.CharField(blank=True, default='Mon,Tue,Wed,Thu,Fri,Sat', help_text='Comma-separated days, e.g. Mon,Tue,Wed', max_length=255)),
                ('availability_start', models.TimeField(default='09:00')),
                ('availability_end', models.TimeField(default='18:00')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='services.servicecategory')),
            ],
            options={
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
    ]
