# Generated by Django 5.0.9 on 2026-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Optional: pin your exact location so nearby customers find you.', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
