# Generated by Django 5.0.9 on 2026-08-18 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('preferred_payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], default='upi', help_text='How the customer plans to pay once the job is completed.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_note', models.CharField(blank=True, help_text='Optional note from provider, e.g. reason for rejection', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
