# Generated by Django 5.0.9 on 2026-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_payment_method',
            field=models.CharField(choices=[('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], default='upi', help_text='How the customer plans to pay once the job is completed.', max_length=20),
        ),
    ]
